version: '3.8'

services:
  app:
    build: .
    container_name: laravel-app
    ports:
      - "80:80"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=bhnqbqmw4ym3cnzcnoel-mysql.services.clever-cloud.com
      - DB_PORT=3306
      - DB_DATABASE=bhnqbqmw4ym3cnzcnoel
      - DB_USERNAME=uf79aqwxzq4tbhib
      - DB_PASSWORD=djvxMUjDLo6AxnSHXnxp
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: task_manager
    ports:
      - "3306:3306"
