version: '3.8'

services:
  app:
    build: .
    container_name: laravel-app
    ports:
      - "80:80"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=sql303.infinityfree.com
      - DB_PORT=3306
      - DB_DATABASE=if0_38073827_task_manager
      - DB_USERNAME=if0_38073827
      - DB_PASSWORD=bUChRZuc7VzpFtx
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: task_manager
    ports:
      - "3306:3306"
