version: '3.8'

services:
  app:
    build: .
    container_name: laravel-app
    ports:
      - "80:80"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql.smtacademy.org
      - DB_PORT=3306
      - DB_DATABASE=smtacade_task
      - DB_USERNAME=smtacade_task
      - DB_PASSWORD="Ibnsaeed01
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: task_manager
    ports:
      - "3306:3306"
